'use strict';
const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
const houses={borovice:{name:'Chata Borovice',price:3200,max:4},kapradina:{name:'Chata Kapradina',price:4500,max:6},vyhlidka:{name:'Apartmá Vyhlídka',price:2700,max:2}};
const fmt=n=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(n);
const pictures=[
['chata-les','Lesní architektura','chaty'],['chata-vecer','Chata za soumraku','chaty'],['chata-sklo','Designová chata v přírodě','chaty'],['chata-zapad','Dřevěná chata','chaty'],['chata-norsko','Skandinávský dům v lese','chaty'],['chata-zima','Zimní chata mezi stromy','chaty'],['chata-vyhled','Výhled z lesní chaty','chaty'],['chata-krajina','Dřevěná chata v horách','chaty'],
['interier-postel','Ložnice v chatě','interiery'],['interier-vyhled','Interiér dřevěné chaty','interiery'],['interier-ram','Útulné posezení','interiery'],['interier-okno','Pokoj s výhledem','interiery'],['interier-ohen','Odpočinek v interiéru','interiery'],['interier-krb','Chvíle u krbu','interiery'],['interier-kuchyne','Kuchyně v chatě','interiery'],['interier-koupelna','Koupelna s vanou','interiery'],['interier-rano','Ráno v útulné ložnici','interiery'],['interier-les','Ložnice otevřená do lesa','interiery'],
['priroda-mlha','Ranní lesy v mlze','priroda'],['priroda-slunce','Slunce nad mlhavým lesem','priroda'],['priroda-hory','Lesní krajina shora','priroda'],['priroda-jezero','Jezero obklopené lesy','priroda'],['priroda-udoli','Horské jezero','priroda'],['priroda-stezka','Prosluněná lesní stezka','priroda']];
const rateItems=[['Chata Borovice','2–4 hosté · cena za noc','3 200 Kč'],['Chata Kapradina','2–6 hostů · cena za noc','4 500 Kč'],['Apartmá Vyhlídka','1–2 hosté · cena za noc','2 700 Kč'],['Snídaňový koš','Na osobu a noc','390 Kč'],['Balíček dřeva','Jednorázově za pobyt','250 Kč'],['Pozdní odjezd','Po předchozí domluvě','600 Kč'],['Pobyt s mazlíčkem','Za zvíře a noc','350 Kč'],['Uvítací balíček','Jednorázově','450 Kč'],['Květiny na pokoj','Jednorázově','590 Kč'],['Piknikový koš','Pro dvě osoby','790 Kč'],['Zapůjčení kol','Kolo na den','490 Kč'],['Sada na grilování','Jednorázově','350 Kč'],['Dětská postýlka','Za celý pobyt','zdarma'],['Parkovací místo','Jedno auto / noc','zdarma'],['Příprava překvapení','Jednorázově','690 Kč'],['Lesní snídaňový brunch','Na osobu','540 Kč'],['Bylinkový čajový set','Jednorázově','190 Kč'],['Doplňkové povlečení','Za sadu','160 Kč'],['Základní závěrečný úklid','Při standardním použití','v ceně'],['Sleva při 4+ nocích','Z ceny ubytování','−10 %']];
$('#rateList').innerHTML=rateItems.map(([name,desc,price])=>`<div class="rate-row"><div><strong>${name}</strong><small>${desc}</small></div><span>${price}</span></div>`).join('');
$('#year').textContent=new Date().getFullYear();
const grid=$('#galleryGrid');let filtered=pictures,lightboxIndex=0;const lightbox=$('#lightbox');
function renderGallery(cat='all'){filtered=pictures.filter(p=>cat==='all'||p[2]===cat);grid.replaceChildren();filtered.forEach((p,i)=>{const button=document.createElement('button');button.className='gallery-thumb';button.type='button';button.setAttribute('aria-label',`Otevřít fotografii: ${p[1]}`);const img=document.createElement('img');img.src=`assets/images/${p[0]}.webp`;img.alt=p[1];img.loading='lazy';const caption=document.createElement('span');caption.textContent=`${p[1]} ↗`;button.append(img,caption);button.addEventListener('click',()=>openPhoto(i));grid.appendChild(button)})}
function openPhoto(i){lightboxIndex=(i+filtered.length)%filtered.length;const p=filtered[lightboxIndex];$('#lightboxImage').src=`assets/images/${p[0]}.webp`;$('#lightboxImage').alt=p[1];$('#lightboxCaption').textContent=`${p[1]} · ${lightboxIndex+1} / ${filtered.length} · ilustrační fotografie`;if(!lightbox.open)lightbox.showModal()}
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',String(n===b))});renderGallery(b.dataset.filter)}));renderGallery();
$('#lightboxClose').onclick=()=>lightbox.close();$('#lightboxPrev').onclick=()=>openPhoto(lightboxIndex-1);$('#lightboxNext').onclick=()=>openPhoto(lightboxIndex+1);lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});document.addEventListener('keydown',e=>{if(lightbox.open&&e.key==='ArrowRight')openPhoto(lightboxIndex+1);if(lightbox.open&&e.key==='ArrowLeft')openPhoto(lightboxIndex-1)});
const menu=$('#menuToggle'),nav=$('#nav');menu.onclick=()=>{const active=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(active));menu.setAttribute('aria-label',active?'Zavřít menu':'Otevřít menu');nav.classList.toggle('open',active)};$$('a',nav).forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Otevřít menu')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});$$('.reveal').forEach(e=>observer.observe(e));
function localDate(offset=0){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
const from=$('#dateFrom'),to=$('#dateTo');from.min=localDate();to.min=localDate(1);$('#quickFrom').min=localDate();$('#quickTo').min=localDate(1);
function nightsBetween(a,b){if(!a||!b)return 0;const av=Date.parse(a+'T12:00:00Z'),bv=Date.parse(b+'T12:00:00Z');return Number.isFinite(av)&&Number.isFinite(bv)?Math.round((bv-av)/86400000):0}
function calc(){const house=houses[$('#house').value],guests=Number($('#guests').value),pets=Number($('#pets').value),nights=nightsBetween(from.value,to.value);const valid=nights>0&&from.value>=localDate()&&guests<=house.max;const stay=valid?house.price*nights:0,discount=valid&&nights>=4?Math.round(stay*.1):0,extras=valid?(pets*nights*350+($('input[value="breakfast"]').checked?390*guests*nights:0)+($('input[value="firewood"]').checked?250:0)+($('input[value="late"]').checked?600:0)):0;$('#nightsLabel').textContent=valid?`${nights} ${nights===1?'noc':nights>=2&&nights<=4?'noci':'nocí'}`:'Zvolte datum';$('#stayPrice').textContent=valid?fmt(stay):'—';$('#discountPrice').textContent=valid?fmt(-discount):'—';$('#extrasPrice').textContent=valid?fmt(extras):'—';$('#totalPrice').textContent=valid?fmt(stay-discount+extras):'—';return{valid,house,guests,nights,total:stay-discount+extras}}
function adjust(){to.min=from.value||localDate(1);if(to.value&&to.value<=from.value)to.value='';const max=houses[$('#house').value].max;$$('#guests option').forEach(o=>o.disabled=Number(o.value)>max);if(Number($('#guests').value)>max)$('#guests').value=String(max);calc()}
$$('#reservationForm input,#reservationForm select').forEach(el=>el.addEventListener('input',adjust));from.addEventListener('change',adjust);to.addEventListener('change',calc);
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),4500)}
$$('[data-house]').forEach(b=>b.addEventListener('click',()=>{$('#house').value=b.dataset.house;adjust();$('#rezervace').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});toast(`Vybrali jste ${houses[b.dataset.house].name}. Zadejte termín pobytu.`)}));
$('#quickBook').onclick=()=>{$('#house').value=$('#quickHouse').value;from.value=$('#quickFrom').value;to.value=$('#quickTo').value;$('#guests').value=$('#quickGuests').value;adjust();$('#rezervace').scrollIntoView({behavior:'smooth'});if(!from.value||!to.value)toast('Zvolte termín příjezdu a odjezdu pro výpočet ceny.');else toast('Pobyt jsme načetli do plánovače. Zde uvidíte orientační cenu.')};
$('#reservationForm').addEventListener('submit',event=>{event.preventDefault();const data=calc(),error=$('#formError');error.textContent='';if(!data.valid){error.textContent=Number($('#guests').value)>data.house.max?'Zvolená chata nemá kapacitu pro tento počet hostů.':'Zvolte platné datum příjezdu (ode dneška) a odjezdu alespoň o den později.';error.scrollIntoView({block:'center'});return}const form=$('#reservationForm');if(!form.checkValidity()){const invalid=$$('input,select,textarea',form).find(el=>!el.checkValidity());error.textContent=invalid=== $('#demoConsent')?'Nejprve prosím potvrďte, že rozumíte demonstrační povaze formuláře.':'Vyplňte prosím správně své jméno, e-mail a povinná pole.';invalid?.focus();return}const summary=$('#confirmSummary');summary.replaceChildren();const lines=[['Místo',data.house.name],['Termín',`${new Date(from.value+'T12:00:00').toLocaleDateString('cs-CZ')} – ${new Date(to.value+'T12:00:00').toLocaleDateString('cs-CZ')}`],['Počet nocí',String(data.nights)],['Hosté',String(data.guests)],['Orientační celková cena',fmt(data.total)]];lines.forEach(([key,value])=>{const div=document.createElement('div');const b=document.createElement('strong');b.textContent=key+': ';div.append(b,document.createTextNode(value));summary.appendChild(div)});$('#confirmation').showModal()});$('#confirmClose').onclick=()=>$('#confirmation').close();$('#confirmation').addEventListener('click',e=>{if(e.target===$('#confirmation'))$('#confirmation').close()});calc();
